### PR TITLE
Add a basic table to csv plugin with test suite.

### PR DESCRIPTION
**Pull request by TriathlonCodes**

### CODE REVIEW

**Comment by TriathlonCodes** [comment]
## CSV Translator

This new class within the Polo module will all you to easily export a table to csv. A different file will be needed for each table, otherwise on calling to_csv each table will overwrite each other. 

### Using CSVTranslator

<pre><code>
a = Polo::CSVTranslator.new(AR::Chef, "chefs.csv")
a.to_csv

# creates a file by the name of chefs.csv will all rows including headers
</code></pre>

### Potenital Areas for Growth:

An additional feature would include a reverse operation, taking a csv and parsing it to a table. A necessary part of this would include needing an options hash to allow for different formats to come in from the csv file other than the default of string.

**Comment by nettofarah** [comment]
hello, @TriathlonCodes!
Thank you for your PR.

I'll look into it a little more carefully tomorrow or sometime during the week.

**Comment by nettofarah** [comment]
One thing I just noticed though.
It looks like you're not using `Polo::Collector` to collect the initial data.

While your solution exports a table to csv, it is not fully using Polo's features.
e.g. Defining a dependency tree and traversing it.

Maybe we can start by using `Polo::Collector` and then sending the data over to your CSV translator?

Another thing you need to keep in mind is that your translator would need to implement these advanced options as well: https://github.com/IFTTT/polo#advanced-usage

**Comment by TriathlonCodes** [comment]
Thanks, I'll look into it! Always happy to dive a little deeper.

**Comment by nettofarah** [comment]
Great, @TriathlonCodes!
Let me know if there's anything I can do to help.

**Comment by nettofarah** [comment]
hi, @TriathlonCodes.
Have you had a chance to look into this?

**Comment by nettofarah** [comment]
Hey, @TriathlonCodes.
Any updates?

**Comment by nettofarah** [comment]
Hi, @TriathlonCodes.
I'm closing the PR.

We can reopen it at any time if you decide to do more work on it.

**Pull request closed without merging**
