### PR TITLE
Add support to serialized fields with AR 5

### PR DESCRIPTION
**Pull request by nettofarah**
This commit enables full support to ActiveRecord 5.
Our biggest change here is the use of the `type_caster` provided by the arel table.
This is done like this so we can support custom field serializers.

cc @rf-

### CODE REVIEW

**Comment by dv** [comment]
This branch gives me a ton of new deprecation warnings:
```

**Comment by nettofarah** [comment]
Yeah, I'm still working on it.

I have considered releasing it as is though, so I can start unblocking people on Rails 5.

The funny thing about this is that I don't think we're actually making calls that trigger these warnings directly.

My guess is that these warnings are being generated by some internal active record calls.

**Comment by nettofarah** [comment]
@dv did you run into any problems using this branch? (other than the warnings)

**Comment by dv** [comment]
@nettofarah yeah maybe release it as a `beta`-named gem, so people who want to upgrade to Rails 5 have a way to do so without pointing to github/master, but also to signify it's not yet 100% complete.

I did not run into any problems, but we haven't put it in production yet so it's not been thoroughly worked through either. If we do run into anything I'll make sure to let you know and help find a solution.

Investigated it a bit but can't figure out how to make it go away. Created an [arel issue](https://github.com/rails/arel/issues/452) about it, maybe there's something obvious I'm missing.

**Comment by dv** [comment]
Seem to have found a solution which I submitted in https://github.com/IFTTT/polo/pull/44

**Pull request merged**
