### PR TITLE
Rails7 support

### PR DESCRIPTION
**Pull request by jdelStrother**
I was struggling to get tests running locally, but hopefully Travis will tell us it's ok...? 😬

### CODE REVIEW

**Comment by jakeonfire** [comment]
i don't see travis builds 🤔

**Comment by jakeonfire** [comment]
looks like travis-ci.org "ceased operations" in favor of travis-ci.com. @lindentibbets do you think we should set up a new free account at travis-ci.com?

**Comment by jakeonfire** [comment]
@jdelStrother i was able to get specs on your branch to pass after updating the ruby version to 2.7.x, a requirement of `activerecord` 7. can you rebase on latest `IFTTT:master` and try again? the instructions are at the bottom of [the readme](https://github.com/IFTTT/polo/blob/master/README.md). also, you should commit your auto-generated `gemfiles/rails70.gemfile` and include it with the PR.

**Comment by jdelStrother** [comment]
@jakeonfire thanks, pushed an update

**Pull request merged**
