### PR TITLE
Ignore virtual attributes

### PR DESCRIPTION
**Pull request by slowjack2k**
This is a fix for #12 . It also changes Quoting for table und columns names.

### CODE REVIEW

**Comment by nettofarah** [comment]
@slowjack2k  do we need tables and columns to be quoted differently?

**Comment by nettofarah** [comment]
Also, can you change the commit message so it follows this style?
http://chris.beams.io/posts/git-commit/

**Comment by slowjack2k** [comment]
Rails provides 2 different methods for quoting table names and columns. As default `quote_table_name` falls back to `quote_column_name`, but it's database dependent. Maybe there are some databases out there which treat table and column quotes differently. Using both is a save bet.

And about the commit message, sorry but this article is to long to read. It is maybe a good stuff but I wan't read it in the near future. Please provide a short instruction.

**Comment by nettofarah** [comment]
hey, @slowjack2k.
I think I'd rather wait until we have a problem with database fields before changing the way we quote fields.

Can you update the PR to include only the missing attributes change?

re: commit message. the explanation in the blog post is great, you should take some time to read it.

**Comment by slowjack2k** [comment]
With postgres you need to use double quotes instead of backticks to quote table and column names.  Sqlite uses both. So you have to change quoting any way if you want to support postgres.

I did give this gem only a try and I will not use it. In that case I 'm not eager to get this patch into your gem. 

You can close this pr and the issue. 

Thanks


Am 25. November 2015 23:56:34 MEZ, schrieb Netto Farah <notifications@github.com>:

**Comment by nettofarah** [comment]
No problem. Thank you for reporting the bug.

**Pull request closed without merging**
