### PR TITLE
Rails 5.2 support

### PR DESCRIPTION
**Pull request by jdelStrother**
Hi there - this PR adds 5.1 & 5.2 gemfiles for Travis, and fixes up raw_sql to work in 5.2.   WDYT?

### CODE REVIEW

**Comment by jdelStrother** [comment]
I have no idea what's up with that Travis failure, can't seem to reproduce it.  Any hints?

**Comment by gregmolnar** [comment]
@nettofarah @nickyleach Any chance of merging this?

**Comment by gregmolnar** [comment]
This PR looks good to me, and Rails 5.2 is out for 3 months now, would it be possible to merge this @nettofarah @jdelStrother ?

**Comment by jdelStrother** [comment]
FWIW we've been running this branch in production on Rails 5-2-stable without discovering any issues.

**Comment by nettofarah** [comment]
This PR looks awesome.
Thank you, @jdelStrother.

I no longer work at IFTTT, so I won't be able to publish the gem, but I can merge this PR into master for you 💃

**Pull request merged**
