### PR TITLE
Postgres Support

### PR DESCRIPTION
**Pull request by derencius**
This pull request will allow the basic features of polo to work with postgres.

### CODE REVIEW

**Comment by derencius** [comment]
But if the on_duplicate feature is used, the generated SQL is going to be invalid because postgres doesn't support _INSERT IGNORE_ and _ON DUPLICATE KEY UPDATE_  features out-of-box yet. What would be an appropriate solution for this? An alert or stop the process?

**Comment by nettofarah** [comment]
Hey, @derencius.
Thank you for submitting this PR.
You're correct, there's no easy implementation of the `on_duplicate` options for PostgreSQL.

I agree that it would make sense to raise an exception when someone tries to use `on_duplicate` in their `Polo.configure` block.

Btw, can you rebase your branch on top of master as opposed to merging it? That way it would keep Polo's history cleaner.

After you do that, can you please squash all the commits and use this standard for the commit message?
http://chris.beams.io/posts/git-commit/

This is looking awesome! Can't wait to :ship: this!

**Comment by bbonamin** [comment]
@derencius @nettofarah  AFAIK postgres will start supporting something similar to INSERT IGNORE or ON DUPLICATE UPDATE starting on 9.5 https://wiki.postgresql.org/wiki/UPSERT

**Comment by bbonamin** [comment]
By the way, does this feature work with associations? When I tried this branch, it didn't work for me. It only generated the "base" insert statement @derencius

**Comment by nettofarah** [comment]
I sounds like we're gonna have to tackle https://github.com/IFTTT/polo/issues/23 before we fiddle with this PR some more.

What do y'all think?

**Comment by derencius** [comment]
@bbonamin how did you try it? did you specify the branch in your Gemfile? 

`gem 'polo', github: 'derencius/polo', branch: 'postgres'`

**Comment by derencius** [comment]
@nettofarah not sure about the way to prevent the usage of `on_duplicate_strategy`. any suggestion?

**Comment by nettofarah** [comment]
@derencius I think we could leave this as is for now, assuming everything works.
I've been thinking about creating multiple translators, one for each database adapter.

We could implement a postgres one that just raises an error when trying to use one of these features in run time.

Another option would be to check when calling `Polo.configure`, though I think that could become a little cumbersome.

In any case, I think your PR looks great, and we should be able to merge it at any time. We can open a new issue for the `on_duplicate` strategy improvements.

**Comment by bbonamin** [comment]
@derencius I just tried again and it follows associations as you would expect! My bad :smile:

**Comment by nettofarah** [comment]
Alright alright!
I think we're good to go then!

congrats @derencius on your awesome PR.
And thank you everyone for helping out.

**Comment by derencius** [comment]
:100: :tada:

**Pull request merged**
