### PR TITLE
Escape columns in DUPLICATE KEY statements

### PR DESCRIPTION
**Pull request by jdelStrother**
I ran into this because I have a table with a column named `key`.   WDYT?

### CODE REVIEW

**Comment by nettofarah** [comment]
This looks great!
Thank you 😊

**Comment by nettofarah** [comment]
I'll publish a new version of the gem when I have a chance sometime this weekend!

Thank you again 😄

**Comment by jdelStrother** [comment]
If you get chance, would be great to get this published :)

**Comment by nettofarah** [comment]
hey, @jdelStrother.
I'm so sorry it took me so long to publish this.

We should be good now. Thanks again for the pull request!

Please check out our survey if you have a chance.
https://github.com/IFTTT/polo/issues/19

**Comment by jdelStrother** [comment]
Done!

**Pull request merged**
